server:
  port: 8082
  servlet:
    context-path: /hotelsUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/hotelsMicroservices
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    import: optional:configserver:http://localhost:8089
  profiles:
    active: hotel
