server:
  port: 8089

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LuisFlorezP/config-microservices
          clone-on-start: true
