server:
  port: 8083
  servlet:
    context-path: /qualificationsUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  data:
    mongodb:
      database: qualificationsMicroservices
  application:
    name: SERVICE-QUALIFICATION
  cloud:
    discovery:
      client:
        simple:
          service-uri: http://localhost:8761/eureka
