server:
  port: 8083
  servlet:
    context-path: /qualificationsUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  data:
    mongodb:
      database: qualificationsMicroservices

