server:
  port: 8081
  servlet:
    context-path: /usersUdemy

springdoc:
  swagger-ui.path: /swaggerDocs
  api-docs.enabled: true
  swagger-ui.enabled: true

spring:
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=usersMicroservices;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.SQLServerDialect
  config:
    import: optional:configserver:http://localhost:8089
